$hypr = ~/.config/hypr
$hl = $hypr/hyprland
$cConf = ~/.config/caelestia

# Variables (colours + other vars)
exec = cp -L --no-preserve=mode --update=none $hypr/scheme/default.conf $hypr/scheme/current.conf
source = $hypr/scheme/current.conf
source = $hypr/variables.conf

# Maybe create hyprland configs
exec = $hypr/scripts/configs.fish $cConf

# User variables
source = $cConf/hypr-vars.conf

# Default monitor conf
monitor=eDP-1,2560x1440@165,0x0,1.33

#Configs
source = $hl/env.conf
source = $hl/general.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/animations.conf
source = $hl/decoration.conf
source = $hl/group.conf
source = $hl/execs.conf
source = $hl/rules.conf
source = $hl/gestures.conf
source = $hl/keybinds.conf
source = $hl/scrolling.conf

# User configs
source = $cConf/hypr-user.conf

# For GTK apps (Gnome-based)

# For Qt apps (KDE/Anki/etc)
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# For Electron apps (Discord, VS Code, Obsidian)
# You can force them to run natively in Wayland so they bypass XWayland entirely
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

env = XCURSOR_SIZE,24

# Flawed-Shell begin
exec-once = { sleep 1; env MALLOC_CONF='narenas:2,background_thread:true,dirty_decay_ms:1000,muzzy_decay_ms:1000' qs -p "/home/flawed/.config/Flawed-Shell/shell.qml"; }
exec-once = awww-daemon
exec-once = awww img /home/flawed/Pictures/Wallpapers/wallpaperflare.com_wallpaper.jpg
# Flawed-Shell end

exec-once = xwayland-satellite

# App Launcher
bind = SUPER, space, exec, wofi --show drun

bind = SUPER, l, exec, hyprlock

# Screenshot
bind = SUPER SHIFT, s, exec, hyprshot -m region

#killactive
bind = SUPER, q, killactive

#floating
bind = SUPER, o, togglefloating

