background {
    monitor =
    path = /home/flawed/Pictures/Wallpapers/wallpaperflare.com_wallpaper.jpg
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.15
    outer_color = rgba(0, 0, 0, 0.5)
    inner_color = rgba(200, 200, 200, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = $ATTEMPTS failed
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
}

label {
    monitor =
    text = $TIME
    text_align = center
    font_size = 80
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
